name: Continuous Integration
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint

  build:
    name: Build
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build

  test:
    name: Test
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run test

  commitlint:
    name: Commit lint
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Commitlint
        run: git log -1 --pretty=format:"%s" | yarn commitlint
