name: Continuous Deployment (experimental)

on:
    push:
        branches:
            - experimental

jobs:
    publish:
        if: github.event_name == 'push' && github.ref == 'refs/heads/experimental'
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  # pulls all commits (needed for lerna / semantic release to correctly version)
                  fetch-depth: "0"

            - name: Configure git user
              run: |
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"

            - name: Authenticate with Registry
              run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Commitlint
              run: git log -1 --pretty=format:"%s" | yarn commitlint

            - name: Build
              run: yarn build

            - name: Lerna Version
              run: yarn lerna version prerelease

            - name: Publish
              run: lerna publish from-package --yes
