name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"

      - name: Setup | Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com/"

      - name: Setup | Ensure registry access
        run: npm whoami --registry https://npm.pkg.github.com/

      - name: Setup | Configure git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Setup | Yarn Install
        uses: bahmutov/npm-install@v1

      - name: Prepare | Lerna Version
        run: yarn lerna version --create-release github --yes

      - name: Prepare | Build
        run: yarn build

      - name: Release | Lerna Publish
        run: lerna publish from-package --yes

      - name: Cleanup | Save Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          path: lerna-debug.log
